# file: gitlab_group_members_addition.yml
- name: GitLab Group Members Management | Add a User to Service Delivery GitLab Group
  gitlab_group_members:  
    server_url: '{{ server_url }}'
    access_token: '{{ access_token }}'
    gitlab_group: 'Service Delivery'
    gitlab_user: '{{ item }}'
    access_level: 'developer'
    state: present
  loop:
    - username_example_1
    - username_example_2
    - username_example_3
  register: group_members

- name: GitLab Group Members Management | Install Python library dependencies to filter out the result
  pip:
    name: jmespath
  
- name: GitLab Group Members Management | Print out a report for the change made by the previous task
  debug:
    msg: "{{ groups_members | json_query('results[*].result') }}"