# file: gitlab_group_members_removal.yml
- name: GitLab Group Members Management | Remove a User from Service Delivery GitLab Group
  gitlab_group_members:
    server_url: '{{ server_url }}'
    access_token: '{{ access_token }}'
    gitlab_group: 'Service Delivery'
    gitlab_user: '{{ item }}'
    state: absent
  loop:
    - username_example_1
    - username_example_2
    - username_example_3
  register: group_members

- name: GitLab Group Members Management | Print out a report for the change made by the previous task
  debug:
    msg: "{{ groups_members | json_query('results[*].result') }}"