# file: gitlab_group_members_addition.yml
- name: GitLab Group Members Management | Add a User to Service Delivery GitLab Group
  gitlab_group_members:  
    server_url: '{{ server_url }}'
    access_token: '{{ access_token }}'
    gitlab_group: '{{ item.groupname }}'
    gitlab_user: '{{ item.username }}'
    access_level: '{{ item.accesslevel }}'
    state: present
  loop: '{{ csv_data }}'
  register: group_members

- name: GitLab Group Members Management | Install Python library dependencies to filter out the result
  pip:
    name: jmespath
  
- name: GitLab Group Members Management | Print out a report for the change made by the previous task
  debug:
    msg: "{{ groups_members | json_query('results[*].result') }}"