# file: jenkins_user_creation.yml
- name: User Management on Jenkins Server | Generate a CRUMB token to be used besides API token to authenticate and make the requested changes on Jenkins server
  uri:
    url: http://{{ server_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)
    user: "{{ login_user }}"
    password: "{{ api_token }}"
    force_basic_auth: yes
    return_content: yes
  register: jenkins_crumb

- name: User Management on Jenkins Server | Create a User Account on Jenkins
  uri:
    url: 'http://{{ server_url }}/securityRealm/createAccountByAdmin'
    user: "{{ login_user }}"
    password: "{{ api_token }}"
    force_basic_auth: yes
    follow_redirects: all
    headers:
        Jenkins-Crumb: "{{ jenkins_crumb.content.split(':')[1] }}"
        Cookie: "{{ jenkins_crumb.set_cookie }}"
    method: POST
    body: '\
        username={{ item.username }}&\
        password1={{ item.password }}&\
        password2={{ item.password }}&\
        fullname={{ item.fullname }}&\
        email={{ item.email }}'
  loop: "{{ csv_data }}"