# file: ~/ansible-sre/roles/statuspage/tasks/main
- name: Manage the creation and the removal of a user account on StatusPage | Create a user account on StatusPage
  uri:
    url: "https://api.statuspage.io/v1/organizations/{{ sp_organization_id }}/users"
    method: POST
    headers:
      Authorization: "Authorization: OAuth {{ sp_authorization_oauth }}"
    body_format: json
    body:
      user:
        email: "{{ item.user_email }}"
        password: "{{ item.user_password }}"
        first_name: "{{ item.first_name }}"
        last_name: "{{ item.last_name }}"
    status_code: 201
    return_content: yes
    validate_certs: no
  loop: "{{ csv_data }}"
  tags:
    - user_addition

- name: Manage the creation and the removal of a user account on StatusPage | Get a List of Users on StatusPage
  uri:
    url: "https://api.statuspage.io/v1/organizations/{{ sp_organization_id }}/users"
    method: GET
    headers:
        Authorization: "Authorization: OAuth {{ sp_authorization_oauth }}"
    body_format: json
    status_code: 200
    return_content: yes
    validate_certs: no
  register: get_users_response
  tags:
    - user_removal

- name: Manage the creation and the removal of a user account on StatusPage | Set a List of the User Ids to Pass to Delete Request
  set_fact:
    user_id: "{{ user_id }} + [ '{{ item[0].id }}' ]"
  with_nested: 
    - "{{ get_users_response.json }}"
    - "{{ csv_data }}"
  when: item[0].email == item[1].email
  vars:
    user_id: []
  tags:
    - user_removal

- name: Manage the creation and the removal of a user account on StatusPage | Delete a user account from StatusPage
  uri:
    url: "https://api.statuspage.io/v1/organizations/{{ sp_organization_id }}/users/{{ item }}"
    method: DELETE
    headers:
      Authorization: "Authorization: OAuth {{ sp_authorization_oauth }}"
    status_code: 200
    return_content: yes
    validate_certs: no
  loop: "{{ user_id }}"
  tags:
    - user_removal