# file: statuspage_user_creation.yml
- name: Manage the creation and the removal of a user account on StatusPage | Create a user account on StatusPage
  uri:
    url: "https://api.statuspage.io/v1/organizations/{{ sp_organization_id }}/users"
    method: POST
    headers:
      Authorization: "Authorization: OAuth {{ sp_authorization_oauth }}"
    body_format: json
    body:
      user:
        email: "{{ item.user_email }}"
        password: "{{ item.user_password }}"
        first_name: "{{ item.first_name }}"
        last_name: "{{ item.last_name }}"
    status_code: 201
    return_content: yes
    validate_certs: no
  loop: "{{ csv_data }}" 
  register: user_response