# file: ~/ansible-sre/roles/pagerduty/tasks/main
- name: PagerDuty User Management | Create a user account on PagerDuty
  pagerduty_user:
    access_token: '{{ pd_api_access_token }}'
    pd_user: '{{ item.fullname }}'
    pd_email: '{{ item.email }}'
    pd_role: '{{ item.pd_role }}'
    pd_team: '{{ item.pd_team }}'
    state: present
  loop: "{{ csv_data }}"
  register: user_accounts
  tags:
    - user_addition

- name: PagerDuty User Management | Remove a user account from PagerDuty
  pagerduty_user:
    access_token: "{{ pd_api_access_token }}"
    pd_user: "{{ item.fullname }}"
    pd_email: "{{ item.email }}"
    state: "absent"
  loop: "{{ csv_data }}"
  register: user_accounts
  tags:
    - user_removal

- name: PagerDuty User Management | Print out a report for the change made by the previous task
  debug:
    msg: "{{ user_accounts | json_query('results[*].result') }}"
  tags:
    - always