# file: zabbix_user_creation.yml
- name: Zabbix User Management | Create a user account on Zabbix
  zabbix_user:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    user_name: "{{ item.username }}"
    name: "{{ item.firstname }}"
    surname: "{{ item.lastname }}"
    user_passwd: "{{ item.password }}"
    user_groups: "{{ item.usergroups }}"
    zabbix_user_type: "{{ item.type }}"
    state: present
  loop: "{{ csv_data }}"
