# file: gitlab_group_members_addition_playbook.yml
- name: GitLab Group Members Management | Add a User to Service Delivery GitLab Group

  vars_files:
    - ../roles/gitlab/vars/gitlab_login_info.yml

  hosts:
    - localhost

  tasks:
    - import_tasks: ../roles/gitlab/tasks/gitlab_group_members_addition.yml