# file: statuspage_user_removal_playbook.yml
- name: Manage the creation and the removal of a user account on StatusPage | Remove a user account from StatusPage
    
vars_files:
  - ../roles/statuspage/vars/statuspage_auth_info.yml

  hosts:
  - localhost

tasks:
  - import_tasks: ../roles/statuspage/tasks/statuspage_user_removal.yml